name: "Java Build Action"
description: "Compile and run Java program "
runs: 
  using: "Composite"
  steps:
    - name: Compile Java
      run: javac Main.java
      shell: bash

    - name: Run Java
      run: java Main
      shell: bash 