name: "Greeting Action"
description: "Receives name and returns message"
inputs:
  username:
  required: true 
  description: "User name"

outputs:
 message:
    description: "Greeting message"
runs: 
using: "Composite"
steps:
  - name: Create Greeting  
    run: echo "message=Hello, ${{inputs.username}}! Welcome" >> $GITHUB_OUTPUT
    shell: bash

  