name: "Java Build Action"
description: "Returns build result"
outputs:
  result: 
  description: "Build result"
  
runs: 
using: "Composite"
steps:
  - name: Set Output 
    run: echo "result=successful" >> $GITHUB_OUTPUT
    shell: bash

  